version: 0.1

environment_variables:
    plaintext:
        XC_ARCH: "386 amd64"
        XC_OS: "linux darwin windows freebsd openbsd"
phases:
  install:
    commands:
      - apt-get update -y
      - env
  pre_build:
      commands:
          - mkdir -p $GOPATH/src/github.com/mitchellh
          - mv $CODEBUILD_SRC_DIR $GOPATH/src/github.com/mitchellh/packer
  build:
    commands:
      - echo Build started on `date`
      - cd $GOPATH/src/github.com/mitchellh/packer
      - make bin
  post_build:
    commands:
      - echo Build completed on `date`
      - ls -R ./pkg
      - ls -R $GOPATH/src/github.com/mitchellh/packer/pkg/
artifacts:
  files:
    - pkg/*
  discard-paths: no
