version: 0.1

environment_variables:
    plaintext:
        XC_ARCH: "386 amd64"
        XC_OS: "linux darwin windows freebsd openbsd"
        PACKER_DIR: "$GOPATH/src/github.com/mitchellh/packer"
phases:
  install:
    commands:
      - apt-get update -y
  pre_build:
      commands:
          - mkdir -p $PACKER_DIR
          - mv $CODEBUILD_SRC_DIR $PACKER_DIR
  build:
    commands:
      - echo Build started on `date`
      - cd $PACKER_DIR
      - make bin
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - $PACKER_DIR/pkg/*
  discard-paths: yes
