version: 0.1

phases:
  install:
    commands:
      - apt-get update -y
  build:
    commands:
      - echo Build started on `date`
      - make bin
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - pkg/*
  discard-paths: yes
