version: 0.1

environment_variables:
    plaintext:
        XC_ARCH: "amd64"
        XC_OS: "linux"
phases:
  install:
    commands:
      - apt-get update -y
      - env
  pre_build:
      commands:
          - mkdir -p $GOPATH/src/github.com/mitchellh
          - mv $CODEBUILD_SRC_DIR $GOPATH/src/github.com/mitchellh/packer
  build:
    commands:
      - echo Build started on `date`
      - cd $GOPATH/src/github.com/mitchellh/packer
      - make bin
  post_build:
    commands:
      - echo Build completed on `date`
      - mv $GOPATH/src/github.com/mitchellh/packer/pkg $CODEBUILD_SRC_DIR
      - cd $CODEBUILD_SRC_DIR
artifacts:
  files:
      - "**/*"
  discard-paths: no
